# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner
  target 'PuppySpa' do
    pod 'AFNetworking', '~> 3.0'
    pod 'SwiftyJSON', '~> 2.3'
  end

end
